# Generated by Django 4.2.7 on 2024-12-04 18:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Poem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("LOVE", "Liefdesgedicht"),
                            ("SEASON", "Seizoensgedicht"),
                            ("BIRTHDAY", "Verjaardagsgedicht"),
                            ("GENERAL", "Algemeen gedicht"),
                        ],
                        default="GENERAL",
                        max_length=10,
                    ),
                ),
                (
                    "season",
                    models.CharField(
                        choices=[
                            ("SPRING", "Lente"),
                            ("SUMMER", "Zomer"),
                            ("AUTUMN", "Herfst"),
                            ("WINTER", "Winter"),
                            ("NONE", "Geen seizoen"),
                        ],
                        default="NONE",
                        max_length=10,
                    ),
                ),
                ("subject", models.CharField(max_length=100)),
                ("mood", models.CharField(max_length=50)),
                ("additional_info", models.TextField(blank=True)),
                ("generated_text", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
