# Generated by Django 4.2.7 on 2024-12-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poems", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="poem",
            name="excluded_words",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="poem",
            name="length",
            field=models.CharField(
                choices=[("SHORT", "Kort"), ("MEDIUM", "Gemiddeld"), ("LONG", "Lang")],
                default="MEDIUM",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="poem",
            name="recipient",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="poem",
            name="style",
            field=models.CharField(
                choices=[
                    ("DEFAULT", "Standaard"),
                    ("HAIKU", "Haiku"),
                    ("LIMERICK", "Limerick"),
                    ("SONNET", "Sonnet"),
                    ("ACROSTICHON", "Acrostichon"),
                    ("CHILDREN", "Kinderlijk"),
                    ("RHYMING", "Rijmend"),
                ],
                default="DEFAULT",
                max_length=15,
            ),
        ),
    ]
