# Generated by Django 4.2.7 on 2024-12-04 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poems", "0002_poem_excluded_words_poem_length_poem_recipient_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="poem",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Gedicht",
                "verbose_name_plural": "Gedichten",
            },
        ),
        migrations.RemoveField(
            model_name="poem",
            name="additional_info",
        ),
        migrations.RemoveField(
            model_name="poem",
            name="subject",
        ),
        migrations.AlterField(
            model_name="poem",
            name="excluded_words",
            field=models.TextField(
                blank=True, help_text="Woorden die niet in het gedicht mogen voorkomen"
            ),
        ),
        migrations.AlterField(
            model_name="poem",
            name="length",
            field=models.CharField(
                choices=[("kort", "Kort"), ("medium", "Gemiddeld"), ("lang", "Lang")],
                default="medium",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="poem",
            name="mood",
            field=models.CharField(
                choices=[
                    ("vrolijk", "Vrolijk"),
                    ("melancholisch", "Melancholisch"),
                    ("romantisch", "Romantisch"),
                    ("inspirerend", "Inspirerend"),
                    ("rustig", "Rustig"),
                ],
                default="vrolijk",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="poem",
            name="recipient",
            field=models.CharField(
                blank=True, help_text="Voor wie is het gedicht bedoeld?", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="poem",
            name="season",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Geen specifiek seizoen"),
                    ("lente", "Lente"),
                    ("zomer", "Zomer"),
                    ("herfst", "Herfst"),
                    ("winter", "Winter"),
                ],
                default="",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="poem",
            name="style",
            field=models.CharField(
                choices=[
                    ("eenvoudig", "Eenvoudig (makkelijk te begrijpen)"),
                    ("modern", "Modern en vrij"),
                    ("rijmend", "Rijmend (traditioneel met rijm)"),
                    ("kinderlijk", "Kinderlijk (speels en simpel)"),
                    ("grappig", "Grappig (met humor)"),
                    ("haiku", "Haiku (3 regels: 5-7-5 lettergrepen)"),
                    ("limerick", "Limerick (5 grappige rijmende regels)"),
                    ("sonnet", "Sonnet (14 regels met vast rijmschema)"),
                    ("acrostichon", "Acrostichon (eerste letters vormen een woord)"),
                    ("romantisch", "Romantisch (liefdevol en warm)"),
                    ("nostalgisch", "Nostalgisch (herinneringen)"),
                    ("inspirerend", "Inspirerend (motiverend)"),
                    ("meditatief", "Meditatief (rustig en beschouwend)"),
                ],
                default="rijmend",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="poem",
            name="theme",
            field=models.CharField(
                help_text="Het thema van het gedicht", max_length=200
            ),
        ),
    ]
