# Generated by Django 4.2.7 on 2024-12-04 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poems", "0003_alter_poem_options_remove_poem_additional_info_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="poem",
            name="ip_address",
            field=models.GenericIPAddressField(
                default="127.0.0.1", help_text="IP adres van de gebruiker"
            ),
        ),
    ]
